### ISSUE TITLE
Implement, export, and document downloadGenomicSequencesFromNCBI()

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BSgenomeForge#1]
This task is part of the "Refactor the BSgenomeForge tools" project. The goal of this project is to replace the old tools that are currently in the **BSgenome** software package with new tools that will be implemented in the **BSgenomeForge** package.

The proposed function (`downloadGenomicSequencesFromNCBI()`) is a utility function that will find and download the `<assembly accession>_<assembly name>_genomic.fna.gz` file (compressed FASTA file) from NCBI, for a given assembly.  It will proceed in 2 steps:
- Use low-level utility `find_NCBI_assembly_ftp_dir()` from the **GenomeInfoDb** package (make sure you have **GenomeInfoDb** >= 1.33.17) to find the FTP directory associated with the specified assembly. Note that the 2 first arguments of `downloadGenomicSequencesFromNCBI` should be the same as `find_NCBI_assembly_ftp_dir`'s arguments.
- Use `download.file()` from the **utils** package to download the `<assembly accession>_<assembly name>_genomic.fna.gz` file.

In addition to the `assembly_accession` and `assembly_name` arguments, `downloadGenomicSequencesFromNCBI()` should have the following arguments:
- `destdir`: A single string that specifies the path to the destination folder. Default value should be `"."`. Tilde-expansion will be supported and performed by `download.file()`.
- `method`: Will be passed down to `download.file()`.
- `quiet`: Will be passed down to `download.file()`.

We'll start with those arguments, so 5 in total. The `download.file()` function has more arguments to control the download (see `?download.file`), but, for the sake of keeping the interface as simple as possible, we won't include them all in `downloadGenomicSequencesFromNCBI`'s interface for now. However, we might add them later as the need arises.

NOTES:
- To work on this task, please fork the **BSgenomeForge** repository. Then do your work on that fork.
- Implement the function in a new file, the `downloadGenomicSequencesFromNCBI.R` file.
- Export the function by adding `export(downloadGenomicSequencesFromNCBI)` to the `NAMESPACE` file.
- Note that `download.file` is already imported (see `importFrom(utils,download.file)` in the `NAMESPACE` file).
- Add a man page for the function, with an example that downloads a _small_ FASTA file (try to find the assembly of a small genome e.g. a microbial genome). Also in the example, show how to import the file in R as a DNAStringSet object.
- Don't forget to add the new files (`downloadGenomicSequencesFromNCBI.R` and `downloadGenomicSequencesFromNCBI.Rd`) to your fork before you commit your work.
- Always test your work before committing. This consists in installing the modified package, starting R, loading the package, and playing around with the new functionality. This process is called "ad hoc manual testing". Once everything behaves and looks as expected, run `R CMD build` and `R CMD check` on the package. Note that `R CMD check` should always be run on the **source tarball** produced by `R CMD build`
- Once your work is ready to be merged, please submit a PR (Pull Request).

**Comment by Priceless-P** [comment]
Hi @hpages , can I work on this task?

**Comment by hpages** [comment]
yep

**Comment by hpages** [comment]
Hi @Priceless-P,

I just merged PR #3.  Also added you as a contributor to the package, and bumped its version. See commit 518c26c9379ea13899cab45fa218642bd91b58e8.

So we can close this now. Thanks again for your contribution!

Best,
H.
