### ISSUE TITLE
forgeBSgenomeDataPkgFromNCBI() enhancement: Programmatically obtain the assembly name from NCBI

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BSgenomeForge#14]
To do after adding the `circ_seqs` argument to the function (issue #13).

**Motivation**

Right now the user must supply the name of the assembly via the `genome` argument. However the question is: is this really necessary? Would it be possible to programmatically obtain this information from NCBI for a given assembly accession? If we were able to do this, then we could get rid of the `genome` argument, and therefore reduce the number of mandatory arguments of the `forgeBSgenomeDataPkgFromNCBI()` function from 4 to 3. This would make the function easier to use, and would also reduce the risk of users making mistakes when they specify the `genome` argument.

**How to programmatically obtain the assembly name**

There are actually several ways to programmatically obtain the assembly name for a given assembly accession.

For example, for the GCF_009729545.1 assembly, one could extract its name (ASM972954v1) by _scraping_ the HTML source of its landing page (located at https://www.ncbi.nlm.nih.gov/assembly/GCF_009729545.1). However, solutions based on HTML scraping tend to be fragile because they are very likely to break when changes are made to the website hosting the HTML documents.

Another solution would be to extract the assembly name from the assembly report (a.k.a. "Full sequence report"). See for example the assembly report for GCF_009729545.1 [here](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/729/545/GCF_009729545.1_ASM972954v1/GCF_009729545.1_ASM972954v1_assembly_report.txt). This is a tabulated file starting with many lines of comment, the first line of comment being:

    # Assembly name:  ASM972954v1

This would be better than scraping HTML but it means that we need to be able to programmatically infer the long and complicated URL to the assembly report. But it turns out that the **GenomeInfoDb** package contains a low-level utility function that solves that part: the `find_NCBI_assembly_ftp_dir()` function (see `?find_NCBI_assembly_ftp_dir` in **GenomeInfoDb**).

Furthermore, in addition to the URL to the FTP dir of the assembly, `find_NCBI_assembly_ftp_dir()` also returns the prefix used in the names of most of the files located in the FTP dir (the 2 things are returned in a character vector of length 2, see the man page for the details). For example:

    library(GenomeInfoDb)
    find_NCBI_assembly_ftp_dir("GCF_009729545.1")
    # [1] "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/729/545/GCF_009729545.1_ASM972954v1"
    # [2] "GCF_009729545.1_ASM972954v1"            

As we can see, this prefix (`GCF_009729545.1_ASM972954v1`) is made of the assembly accession and assembly name put together, and separated with an underscore (`_`). Let's use this to obtain the assembly name!

**Proposal**

- Modify `forgeBSgenomeDataPkgFromNCBI()` to obtain the assembly name programmatically. The code that will obtain the assembly name from the assembly accession should be placed in its own little internal helper function. This helper function should call `find_NCBI_assembly_ftp_dir()`, then extract the assembly name from the value returned by the call. Beware that assembly names can possibly contain underscores (`_`).

- Test this internal helper function extensively. Make sure to test it on assemblies with underscores in their name.

- Once the above is in place and succesfully tested, get rid of the `genome` argument and modify the man page accordingly.

**Comment by kakopo** [comment]
Hi Hervé. I have just pushed this code and created a PR. Let me know what you think. Thanks.

**Comment by hpages** [comment]
I just merged PR #20 so we can close this. Don't forget to resync your fork.

Want to work on issue #19 next? Thx!

**Comment by kakopo** [comment]
Alright!
