### ISSUE TITLE
BSgenomeForge from Ensembl genome

### ISSUE THREAD

**Issue by junjunxy** [Bioconductor/BSgenomeForge#43]
Hi, 

Thank you for developing and maintaining the tool :) 
I am wondering that it is possible to make a Bsgenome object from the fasta file retrieved from Ensembl.

I am following the BSgenomeForge vignette and bit confusing in seed file format. as I understand it seems like have to choose only between NCBI or USCS in several description options. Is it correct? 

Thank you in advance :)

**Comment by hpages** [comment]
Why would you use a FASTA file from Ensembl? AFAIK Ensembl annotations are based on assemblies that are available at NCBI so everything is going to be much easier if you figure out what NCBI assembly they use at Ensembl for your orgnanism. They're all listed in this file: https://ftp.ensembl.org/pub/release-111/species_EnsemblVertebrates.txt
Then simply use `forgeBSgenomeDataPkgFromNCBI()`.

If for whatever reason you absolutely need to use the FASTA file from Ensembl then you will need to create a seed file. This method is agnostic of the provenance of the FASTA file. Make sure to read the "Advanced BSgenomeForge usage" vignette carefully where this is all documented.

H.

**Comment by junjunxy** [comment]
Hi, Thank you for the kinds response :)

I mean, my interested genome was retrieved from the [Ensembl Rapid Release](https://rapid.ensembl.org/index.html), thus it is not updated in BSgenome.

I will try to make BSgenome from FASTA file again with the Advanced BSgenomeForge usage vignette again :)

**Comment by hpages** [comment]
> I mean, my interested genome was retrieved from the Ensembl Rapid Release, thus it is not updated in BSgenome.

Of course we (Bioconductor) don't provide BSgenome packages for the Ensembl Rapid Release genomes. But AFAICT the genomes they use at Ensembl Rapid Release are available at NCBI. So my advice to use `forgeBSgenomeDataPkgFromNCBI()` still applies.

**Comment by junjunxy** [comment]
Thanks for helping me a lot! 😄
It definitely save lots of time!!!
