### ISSUE TITLE
Add 'assembly_accession' argument to fastaTo2bit()

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BSgenomeForge#7]
To do only once PR #6 is merged and issue #5 is closed.

**Proposed improvement to `fastaTo2bit()`**

The function will typically be used on a FASTA file obtained with `downloadGenomicSequencesFromNCBI()`. Note that the FASTA files provided by NCBI don't use the official sequence names for the sequences in the file. Instead, the sequences are named according to their GenBank or RefSeq accession numbers. So when we call `fastaTo2bit()` on the downloaded FASTA file, it will be useful if the function can behave like the `fasta_to_sorted_2bit.R` scripts that people have been using so far to do the FASTA to 2bit conversion. In other words, it will be useful if `fastaTo2bit()` can perform the same kind of sanity checks, sequence renaming, and sequence reordering, that the `fasta_to_sorted_2bit.R` scripts perform.

Examples of `fasta_to_sorted_2bit.R` scripts (these scripts are located in the **BSgenome** package):

- https://github.com/Bioconductor/BSgenome/blob/master/inst/extdata/GentlemanLab/BSgenome.Mfascicularis.NCBI.6.0-tools/fasta_to_sorted_2bit.R
- https://github.com/Bioconductor/BSgenome/blob/master/inst/extdata/GentlemanLab/BSgenome.Amellifera.NCBI.AmelHAv3.1-tools/fasta_to_sorted_2bit.R

In order to perform this kind of sanity checks, sequence renaming, and sequence reordering, `fastaTo2bit()` will need to know the GenBank or RefSeq assembly accession associated with the input FASTA file. The way we will communicate this information to the function is via a 3rd argument, the `assembly_accession` argument. This argument should be set to `NA` by default.

**Typical use**
```
library(BSgenomeForge)

## Download FASTA file containing genomic sequences for Acidianus infernus
## assembly from NCBI (see https://www.ncbi.nlm.nih.gov/assembly/GCF_009729545.1):
fasta_path <- downloadGenomicSequencesFromNCBI("GCF_009729545.1")

## Take a look at the sequence names in this FASTA file:
names(readDNAStringSet(fasta_path))

## Use fastaTo2bit() to convert the file to 2bit. We're using the function in its
## simplest form here so there won't be any sequence renaming or reordering:
fastaTo2bit(fasta_path, "Ainfernus.2bit")

## Take a look at the sequence names in the resulting 2bit file:
names(import.2bit("Ainfernus.2bit"))

## Use fastaTo2bit() again to convert the file to 2bit. This time we want the function
## to rename and reorder the sequences as in getChromInfoFromNCBI("GCF_009729545.1"),
## so we supply "GCF_009729545.1":
fastaTo2bit(fasta_path, "Ainfernus_sorted.2bit", assembly_accession="GCF_009729545.1")

## Take a look at the sequence names in the resulting 2bit file:
names(import.2bit("Ainfernus_sorted.2bit"))
```

**Comment by kakopo** [comment]
Hi @hpages. 
Thank you for the resources shared thus far! I ran into a few issues that I tried to resolve. 
I've just submitted a PR, and I hope it is satisfactory.

**Comment by hpages** [comment]
All looks good. Ready for issue #9?

**Comment by kakopo** [comment]
Yes! Definitely!
